#+TITLE: Bleed and authenticity
#+AUTHOR: Kazuaki Ishiguro
#+LANGUAGE: en
#+OPTIONS: toc:nil num:nil author:t creator:nil html-style:nil
#+HTML_DOCTYPE: html5
#+HTML_LINK_HOME: ../
#+HTML_LINK_UP: ../essay
#+HTML_HEAD: <style>body{font-family:monospace; max-width:33vw;}</style>

"The real thing will bleed when cut."

These words have come to mind recently. I was wondering why the word came up and figured out the reason. It was when I was listening to my favorite Naval Ravikant's podcast in a cult way, he pointed out some keys to becoming a successful business with these terms such as “Escape competition through authenticity.” and "Take business risks under your name." The reason those words remained in impact was that I had a blurry understanding of them in my head, but never actually took action.And these words are coherent and have the importance of not shifting too much when doing something.At the same time, I was convinced that taking the risk of doing something under your name and credibility were synonyms, which may be the reason for naming the company that gains its name when doing business.

"The real thing will bleed when cut."

In other words, what is created from the author's bloody efforts is "real" while the author should take the risk of "bleeding". In today's world, there are many risks with doing under your names because of the Internet, but there are too few authentic pieces.

I wanted to keep this wording in the title as the first post on my site's essay.

-----

「本物は切ったら血が出る」

この言葉がどことなく頭に浮かんできた。なぜ浮かんできたのかを考え理由を探った所、それはその時気に入って半ばカルト的に聞いていたNaval Ravikant氏のポッドキャストで「本物である事によって競合を避けろ」や「実名でビジネスリスクを取れ」等の言葉で溢れていたからだった。それらが印象に残った理由として、頭ではなんとなく理解はしていたが、その時まで実際に行動に起こすことは無かったからだ。そしてこれらの言葉は一貫性があり、何かをする際にブレない事の重要性も兼ね備えている。同時に実名に於いて何かをする事と本物である事は同意語であり、実世界でもビジネスの屋号等を自身の名前にするのはこういう理由からであろうと納得した。

「本物は切ったら血が出る」

言い換えれば、作者の血が通った作品はまぎれもなく「本物」であり、反対に作者は切られる事で「出血」する覚悟をしなければならない。昨今では実名を出すことのリスクはインターネットによって常にあるが、それに伴った本物が少なく感じてしまう。

僕はこの言葉を自身のエッセーの最初のタイトルに博したいと思う。

-----
